export const boky = {
  taloha: [
    { genesisy: 'Genesisy' },
    { eksodosy: 'Eksodosy' },
    { levitikosy: 'Levitikosy' },
    { nomery: 'Nomery' },
    { deoteronomia: 'Deoteronomia' },
    { josoa: 'Josioa' },
    { mpitsara: 'Mptsara' },
    { rota: 'Rota' },
    { 'samoela-voalohany': '1 Samoela' },
    { 'samoela-faharoa': '2 Samoela' },
    { 'mpanjaka-voalohany': '1 Mpanjaka' },
    { 'mpanjaka-faharoa': '2 Mpanjaka' },
    { 'tantara-voalohany': '1 Tantara' },
    { 'tantara-faharoa': '2 Tantara' },
    { ezra: 'Ezra' },
    { nehemia: 'Nehemia' },
    { estera: 'Estera' },
    { joba: 'Joba' },
    { salamo: 'Salamo' },
    { ohabolana: 'Ohabolana' },
    { mpitoriteny: 'Mpitoriteny' },
    { 'tononkirani-solomona': "Tonon-kiran' i Solomona" },
    { isaia: 'Isaia' },
    { jeremia: 'Jeremia' },
    { fitomaniana: 'Fitomaniana' },
    { ezekiela: 'Ezekiela' },
    { daniela: 'Daniela' },
    { Hosea: 'Hosea' },
    { joela: 'Joela' },
    { amosa: 'Amosa' },
    { obadia: 'Obadia' },
    { jona: 'Jona' },
    { mika: 'Mika' },
    { nahoma: 'Nahoma' },
    { habakoka: 'Habakoka' },
    { zefania: 'Zefania' },
    { hagay: 'Hagay' },
    { zakaria: 'Zakaria' },
    { malakia: 'Malakia' },
  ],
  vaovao: [
    { matio: 'Matio' },
    { marka: 'Marka' },
    { lioka: 'Lioka' },
    { jaona: 'Jaona' },
    { 'asanny-apostoly': "Asan'ny Apostoly" },
    { romana: 'Romanina' },
    { '1-korintianina': '1 Korintianina' },
    { '2-korintianina': '2 Korintianina' },
    { galatianina: 'Galatianina' },
    { efesianina: 'Efesianina' },
    { filipianina: 'Filipianina' },
    { kolosianina: 'Kolosianina' },
    { '1-tesalonianina': '1 Tesalonianina' },
    { '2-tesalonianina': '2 Tesalonianina' },
    { '1-timoty': '1 Timoty' },
    { '2-timoty': '2 Timoty' },
    { titosy: 'Titosy' },
    { filemona: 'Filemona' },
    { hebreo: 'Hebreo' },
    { jakoba: 'Jakoba' },
    { '1-petera': '1 Petera' },
    { '2-petera': '2 Petera' },
    { '1-jaona': '1 Jaona' },
    { '2-jaona': '2 Jaona' },
    { '3-jaona': '3 Jaona' },
    { joda: 'Joda' },
    { apokalypsy: 'Apokalypsy' },
  ],
};
